server:
  port: 8083

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://cart-db:5432/cart_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      allow-coerce-as-scalar: false

services:
  product-service:
    url: http://product-service:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ecommerce.cartservice: DEBUG
